### ISSUE TITLE
شرکت های مهاجرتی ارزش دارن؟

### ISSUE THREAD

**Issue by alirstm** [komeilmehranfar/visa-sponsers-companies-for-iranians#6]
تو ایران یه عالمه شرکت های مهاجرتی وجود داره پول میگیرن مشاوره میدن و کمک می کنند برای مهاجرت. اینا ارزش داره؟ یا بهترین راه همینه که خودم رزومه بفرستم به شرکت های خارجی؟

**Comment by komeilmehranfar** [comment]
ببین خیلی بعیده شرکت های مهاجرتی بتونن برات کار پیدا کنن. فوقش بتونن تو فرایند ویزا بهت کمک کنن که اونم خودت میتونی انجام بدی
